fix: swap filenames for book-hold canceling and canceled
ddd-by-examples/library-nestjs pull request #11
Opened 2023-03-14 23:31 UTC by dtojikulov

For some reason `book-hold-canceled.ts` and `book-hold-canceling-failed.ts` events were switched in places, in other words one file was exporting opposing event.

fixed that ;)

2023-03-16 09:52 UTC, MaciejSikorskiRamp requested changes

2023-03-16 09:52 UTC, MaciejSikorskiRamp commented on libs/lending/domain/src/index.ts
> +export * from './lib/events/book-hold-canceled';
I think the previous order was correct

2023-03-16 09:52 UTC, MaciejSikorskiRamp commented on libs/lending/domain/src/lib/patron.ts
> +import { BookHoldCanceled } from './events/book-hold-canceled';
Same here

2023-04-12 14:40 UTC, dtojikulov commented on libs/lending/domain/src/index.ts
> +export * from './lib/events/book-hold-canceled';
done

2023-04-12 14:41 UTC, dtojikulov commented on libs/lending/domain/src/lib/patron.ts
> +import { BookHoldCanceled } from './events/book-hold-canceled';
done

2023-05-11 19:59 UTC, Sikora00 approved these changes

2023-05-11 20:00 UTC, merged